version: "3.7"
services:
  manga-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    volumes:
      - ${PWD}:/app
    command: index.js
